tasks:
    path: /tareas
    controller: App\Controller\TaskController::index

tasks_detail:
    path: /tarea/{id}
    controller: App\Controller\TaskController::detail
    
tasks_edit:
    path: /editar-tarea/{id}
    controller: App\Controller\TaskController::edit 

tasks_delete:
    path: /borrar-tarea/{id}
    controller: App\Controller\TaskController::delete
    
tasks_creation:
    path: /crear-tarea
    controller: App\Controller\TaskController::creation

my_task:
    path: /mis-tareas
    controller: App\Controller\TaskController::myTasks    
    
register:
    path: /registro
    controller: App\Controller\UserController::register
    
login:
    path: /
    controller: App\Controller\UserController::login    
    
logout:
    path: /logout    